sudo: required
language: python
os:
  - linux
python:
  # - "3.5"
  - "3.8"
matrix:
  include:
    # - name: "C++"
    #   language: cpp
    #   install:
    #     - cd python
    #     - mkdir build
    #   script:
    #     - cd build
    #     - cmake ..
    #     - make
    #     - ctest
    # - os: osx
    #   osx_image: xcode8.3
    #   python: "3.6-dev"
    - name: "Web client"
      sudo: required
      addons:
        chrome: stable
      language: node_js
      node_js: node
      before_install:
        - node --version
        - openssl aes-256-cbc -K $encrypted_994f9713e3f3_key -iv $encrypted_994f9713e3f3_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
        - tar -zxvf credentials.tar.gz
        - sudo mkdir /secrets 
        - sudo mv pni-brinacogs-mouse-atlas-617c5e6a1127.json /secrets 
        - rm credentials.tar.gz
      install:
        - npm install
      script:
        # - npm run build
        # - npm run build-min
        # - npm run build-python
        - npm run build-python-min
        # - npm run test
        # - npm run benchmark
      after_success:
        - cp -r ./dist/python-min appengine/frontend/static/
      deploy:
      - provider: gae
        skip_cleanup: true
        keyfile: "/secrets/pni-brinacogs-mouse-atlas-617c5e6a1127.json"
        project: pni-brinacogs-mouse-atlas
        on: master
        no_promote: false # false promotes latest deploy build to receive all traffic
        default: true
        verbosity: error
        config: "./appengine/frontend/app.yaml"
        no_stop_previous_version: false
      
install:
  - pip install tox-travis
script:
  - cd python
#   - tox -vvvvvvv