language: python
os:
  - linux
python:
  # - "3.5"
  - "3.8"
jobs:
  include:
    # - name: "C++"
    #   language: cpp
    #   install:
    #     - cd python
    #     - mkdir build
    #   script:
    #     - cd build
    #     - cmake ..
    #     - make
    #     - ctest
    # - os: osx
    #   osx_image: xcode8.3
    #   python: "3.6-dev"
    - name: "Web client"
      addons:
        chrome: stable
      language: node_js
      node_js: node
      before_install:
        - node --version
        - openssl aes-256-cbc -K $encrypted_994f9713e3f3_key -iv $encrypted_994f9713e3f3_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
        - tar -zxvf credentials.tar.gz
        - cat neuroglancer-braincogs-f855da9d6853.json
        - sudo mkdir /secrets 
        - sudo mv neuroglancer-braincogs-f855da9d6853.json /secrets 
        - rm credentials.tar.gz
      install:
        - npm install
      script:
        # - npm run build
        # - npm run build-min
        # - npm run build-python
        - npm run build-python-min
        # - npm run test
        # - npm run benchmark
      after_success:
        - cp -r ./dist/python-min appengine/frontend/static/
      deploy:
      - provider: gae
        keyfile: "/secrets/neuroglancer-braincogs-f855da9d6853.json"
        project: neuroglancer-braincogs
        on: master
        promote: false 
        edge: true
        verbosity: warning
        config: "./appengine/frontend/app.yaml"
        stop_previous_version: true
      
install:
  - pip install tox-travis
script:
  - cd python
#   - tox -vvvvvvv